#ifndef MININB_CONFIG_H_INCLUDED
#define MININB_CONFIG_H_INCLUDED

/*
 * This file is generated by CMake. The original file is called
 * config.h.cmake. Please do not modify.
 */

#cmakedefine HAVE_LEVELDB 1
#cmakedefine HAVE_NESSDB_V1 1
#cmakedefine HAVE_NESSDB_V2 1
#cmakedefine HAVE_CASCADEDB 1
#cmakedefine HAVE_BERKELEYDB 1
#cmakedefine HAVE_KYOTOCABINET 1
#cmakedefine HAVE_TOKUKV 1

#endif /* MININB_CONFIG_H_INCLUDED */
